config/routes.rb
Rails.application.routes.draw do

  root 'checkouts#index'

  get '/games', to: 'games#index', as: :games
  get '/find', to: 'checkouts#find', as: :find
  get '/admin', to: 'admin#index', as: :admin
  get '/recent', to: 'checkouts#recent', as: :recent
  get '/longest', to: 'checkouts#longest', as: :longest
  get '/loaners', to: 'loaners#index', as: :loaners

  get '/status', to: 'application#app_status', as: :status

  get '/attendee/status', to: 'attendees#status'
  post '/attendee/new', to: 'attendees#new'
  post '/checkout/new', to: 'checkouts#new'
  post '/return', to: 'checkouts#return'

  post '/groups', to: 'loaners#create'
  get '/groups/edit', to: 'loaners#edit'
  put '/groups/:id', to: 'loaners#update'
  get '/groups/cancel', to: 'loaners#cancel'
  delete '/groups/:id', to: 'loaners#delete'

  get '/loaners/group/:id', to: 'loaners#group_index', as: :group
  post '/loan', to: 'loaners#new'

  get '/groups/deleted', to: 'loaners#groups_deleted', as: :groups_deleted
  put '/groups/restore/:id', to: 'loaners#restore'

  get '/admin/setup', to: 'admin#setup', as: :setup
  get '/admin/teardown', to: 'admin#teardown', as: :teardown
  get '/admin/events', to: 'admin#events', as: :events
  get '/admin/cull', to: 'admin#cull', as: :cull
  get '/admin/new_game', to: 'admin#new_game', as: :new_game
  get '/admin/metrics/:event', to: 'admin#metrics', as: :metrics
  get '/admin/purge', to: 'admin#purge', as: :purge
  get '/admin/missing', to: 'admin#missing', as: :missing
  get '/admin/storage', to: 'admin#storage', as: :storage
  get '/admin/added/:event', to: 'admin#added_games', as: :added
  get '/admin/culled/:event', to: 'admin#culled_games', as: :culled

  put '/setup/tag', to: 'admin#setup_tag', as: :setup_tag
  put '/setup/reset', to: 'admin#reset_setup', as: :reset_setup

  post '/admin/events', to: 'events#create'
  get '/admin/events/edit', to: 'events#edit'
  put '/admin/events/:id', to: 'events#update'
  get '/admin/events/cancel', to: 'events#cancel'

  get '/titles', to: 'admin#titles'
  get '/admin/titles/edit', to: 'titles#edit'
  put '/admin/titles/:id', to: 'titles#update'
  get '/admin/titles/cancel', to: 'titles#cancel'

  get '/publishers', to: 'admin#publishers'
  get '/admin/publishers/edit', to: 'publishers#edit'
  put '/admin/publishers/:id', to: 'publishers#update'
  get '/admin/publishers/cancel', to: 'publishers#cancel'

  get '/tournament', to: 'admin#tournament_games'
  post '/admin/tournament', to: 'tournament_games#create'
  get '/admin/tournament/edit', to: 'tournament_games#edit'
  put '/admin/tournament/:id', to: 'tournament_games#update'
  get '/admin/tournament/cancel', to: 'tournament_games#cancel'
  delete '/admin/tournament/:id', to: 'tournament_games#delete'

  get '/tournament/recently_deleted', to: 'tournament_games#recently_deleted'
  put '/admin/tournament/restore/:id', to: 'tournament_games#restore'

  get '/about', to: 'admin#about'

  get '/reports', to: 'admin#reports'
  get '/games/csv', to: 'games#csv'
  get '/titles/csv', to: 'titles#csv'
  get '/checkouts/csv', to: 'checkouts#csv'
  get '/storage/csv', to: 'admin#csv'

  get '/admin/backup', to: 'admin#backup', as: :backup
  post '/backup', to: 'backup#initiate'

  get '/game/status', to: 'games#status'
  post '/game/new', to: 'games#new'
  get '/game/display', to: 'games#display'

  get '/suggestions/:event', to: 'admin#suggestions', as: :suggestions
  post '/suggest', to: 'application#suggest_a_title'

  get '/admin/stats', to: 'admin#stats'

end

app/views/admin/metrics/_checkouts_by_publisher.html.erb
<table class="table table-striped">
    <tr>
        <th class="col-xs-3"></th>
        <th class="col-xs-3">
            Publisher
        </th>
        <th class="col-xs-3">
            Checkouts
        </th>
        <th class="col-xs-3"></th>
    </tr>
    <% @event.checkouts_by_publisher.each_with_index do |s_row, index| %>
        <tr data-event-id="<%= index %>">
            <td class="col-xs-3"></td>
            <td class="col-xs-3">
                <%= s_row['publisher'] %>
            </td>
            <td class="col-xs-3">
                <%= s_row['checkouts'] %>
            </td>
            <td class="col-xs-3"></td>
        </tr>
    <% end %>
</table>

app/views/admin/metrics/_checkouts_by_title.html.erb
<table class="table table-striped">
    <tr>
        <th class="col-xs-3">
            Title
        </th>
        <th class="col-xs-3">
            Publisher(s)
        </th>
        <th class="col-xs-2">
            Checkouts
        </th>
        <th class="col-xs-2">
            Copies During Show
        </th>
        <th class="col-xs-2">
            Checkouts Per Copy
        </th>
    </tr>
    <% @event.checkouts_by_title.each_with_index do |s_row, index| %>
        <tr data-event-id="<%= index %>">
            <td class="col-xs-3">
                <%= s_row['title'] %>
            </td>
            <td class="col-xs-3">
                <%= s_row['publisher'] %>
            </td>
            <td class="col-xs-2">
                <%= s_row['checkouts'] %>
            </td>
            <td class="col-xs-2">
                <%= s_row['copies_during_show'] %>
            </td>
            <td class="col-xs-1">
                <%= s_row['checkouts_per_copy'] %>
            </td>
        </tr>
    <% end %>
</table>

app/views/admin/metrics/_event_checkout_summary.html.erb
<table class="table table-striped">
    <tr>
        <th class="col-xs-1"></th>
        <th class="col-xs-2">
            Date
        </th>
        <th class="col-xs-2">
            Time
        </th>
        <th class="col-xs-2">
            Checkouts
        </th>
        <th class="col-xs-2">
            Returns
        </th>
        <th class="col-xs-2">
            Outstanding Checkouts
        </th>
        <th class="col-xs-1"></th>
    </tr>
    <% @event.event_checkout_summary.each_with_index do |s_row, index| %>
        <tr data-event-id="<%= index %>">
            <td class="col-xs-1"></td>
            <td class="col-xs-2">
                <%= s_row['date'] %>
            </td>
            <td class="col-xs-2">
                <%= s_row['time'] %>
            </td>
            <td class="col-xs-2">
                <%= s_row['checkouts'] %>
            </td>
            <td class="col-xs-2">
                <%= s_row['returns'] %>
            </td>
            <td class="col-xs-2">
                <%= s_row['outstanding_checkouts'] %>
            </td>
            <td class="col-xs-1"></td>
        </tr>
    <% end %>
</table>

app/views/admin/metrics/_games_tracking_summary.html.erb
<div class="row">
    <div class="col-xs-1"></div>
    <div class="col-xs-10">
        <table class="table table-striped" style="border: 1px solid #ccc; border-radius: 4px; border-collapse: unset;">
            <tr>
                <th class="col-xs-2" style="text-align: center;">
                    Active Games
                </th>
                <th class="col-xs-2" style="text-align: center;">
                    Games At Setup
                </th>
                <th class="col-xs-2" style="text-align: center;">
                    Games Culled
                </th>
                <th class="col-xs-2" style="text-align: center;">
                    Games Added
                </th>
                <th class="col-xs-2" style="text-align: center;">
                    Games At Teardown
                </th>
            </tr>
            <% games_tracking_summary = @event.games_tracking_summary.first %>
            <tr>
                <td class="col-xs-2" style="text-align: center;">
                    <%= games_tracking_summary['active_games'] %>
                </td>
                <td class="col-xs-2" style="text-align: center;">
                    <%= games_tracking_summary['games_at_setup'] %>
                </td>
                <td class="col-xs-2" style="text-align: center;">
                    <%= link_to games_tracking_summary['culled_during_show'], culled_path(@event) %>
                </td>
                <td class="col-xs-2" style="text-align: center;">
                    <%= link_to games_tracking_summary['added_during_show'], added_path(@event) %>
                </td>
                <td class="col-xs-2" style="text-align: center;">
                    <%= games_tracking_summary['games_at_teardown'] %>
                </td>
            </tr>
        </table>
    </div>
    <div class="col-xs-1"></div>
</div>

app/views/admin/metrics/_recent_event_summary.html.erb
<div class="row">
    <table class="table table-striped">
        <tr>
            <th class="col-xs-3">
                Event
            </th>
            <th class="col-xs-3">
                Attendees
            </th>
            <th class="col-xs-3">
                Checkouts
            </th>
            <th class="col-xs-3">
                Average Checkout / Attendee
            </th>
        </tr>
        <% @event.recent_event_summary.each_with_index do |s_row, index| %>
            <tr data-event-id="<%= index %>">
                <td class="col-xs-3">
                    <%= s_row['event'] %>
                </td>
                <td class="col-xs-3">
                    <%= s_row['attendees'] %>
                </td>
                <td class="col-xs-3">
                    <%= s_row['checkouts'] %>
                </td>
                <td class="col-xs-3">
                    <%= s_row['avg_co_per_attendee'] %>
                </td>
            </tr>
        <% end %>
    </table>
</div>