config/routes.rb
Rails.application.routes.draw do

  root 'checkouts#index'

  get '/games', to: 'games#index', as: :games
  get '/find', to: 'checkouts#find', as: :find
  get '/admin', to: 'admin#index', as: :admin
  get '/recent', to: 'checkouts#recent', as: :recent
  get '/longest', to: 'checkouts#longest', as: :longest
  get '/loaners', to: 'loaners#index', as: :loaners

  get '/status', to: 'application#app_status', as: :status

  get '/attendee/status', to: 'attendees#status'
  post '/attendee/new', to: 'attendees#new'
  post '/checkout/new', to: 'checkouts#new'
  post '/return', to: 'checkouts#return'

  post '/groups', to: 'loaners#create'
  get '/groups/edit', to: 'loaners#edit'
  put '/groups/:id', to: 'loaners#update'
  get '/groups/cancel', to: 'loaners#cancel'
  delete '/groups/:id', to: 'loaners#delete'

  get '/loaners/group/:id', to: 'loaners#group_index', as: :group
  post '/loan', to: 'loaners#new'

  get '/groups/deleted', to: 'loaners#groups_deleted', as: :groups_deleted
  put '/groups/restore/:id', to: 'loaners#restore'

  get '/admin/setup', to: 'admin#setup', as: :setup
  get '/admin/teardown', to: 'admin#teardown', as: :teardown
  get '/admin/events', to: 'admin#events', as: :events
  get '/admin/cull', to: 'admin#cull', as: :cull
  get '/admin/new_game', to: 'admin#new_game', as: :new_game
  get '/admin/metrics/:event', to: 'admin#metrics', as: :metrics
  get '/admin/purge', to: 'admin#purge', as: :purge
  get '/admin/missing', to: 'admin#missing', as: :missing
  get '/admin/storage', to: 'admin#storage', as: :storage
  get '/admin/added/:event', to: 'admin#added_games', as: :added
  get '/admin/culled/:event', to: 'admin#culled_games', as: :culled

  put '/setup/tag', to: 'admin#setup_tag', as: :setup_tag
  put '/setup/reset', to: 'admin#reset_setup', as: :reset_setup

  post '/admin/events', to: 'events#create'
  get '/admin/events/edit', to: 'events#edit'
  put '/admin/events/:id', to: 'events#update'
  get '/admin/events/cancel', to: 'events#cancel'

  get '/titles', to: 'admin#titles'
  get '/admin/titles/edit', to: 'titles#edit'
  put '/admin/titles/:id', to: 'titles#update'
  get '/admin/titles/cancel', to: 'titles#cancel'

  get '/publishers', to: 'admin#publishers'
  get '/admin/publishers/edit', to: 'publishers#edit'
  put '/admin/publishers/:id', to: 'publishers#update'
  get '/admin/publishers/cancel', to: 'publishers#cancel'

  get '/tournament', to: 'admin#tournament_games'
  post '/admin/tournament', to: 'tournament_games#create'
  get '/admin/tournament/edit', to: 'tournament_games#edit'
  put '/admin/tournament/:id', to: 'tournament_games#update'
  get '/admin/tournament/cancel', to: 'tournament_games#cancel'
  delete '/admin/tournament/:id', to: 'tournament_games#delete'

  get '/tournament/recently_deleted', to: 'tournament_games#recently_deleted'
  put '/admin/tournament/restore/:id', to: 'tournament_games#restore'

  get '/about', to: 'admin#about'

  get '/reports', to: 'admin#reports'
  get '/games/csv', to: 'games#csv'
  get '/titles/csv', to: 'titles#csv'
  get '/checkouts/csv', to: 'checkouts#csv'
  get '/storage/csv', to: 'admin#csv'

  get '/admin/backup', to: 'admin#backup', as: :backup
  post '/backup', to: 'backup#initiate'

  get '/game/status', to: 'games#status'
  post '/game/new', to: 'games#new'
  get '/game/display', to: 'games#display'

  get '/suggestions/:event', to: 'admin#suggestions', as: :suggestions
  post '/suggest', to: 'application#suggest_a_title'

  get '/admin/stats', to: 'admin#stats'

end

app/views/admin/about.html.erb
<% content_for :title, 'Dev Team' %>

<div class="row">
    <div class="col-xs-1"></div>
    <div class="col-xs-10">
        <%= link_to 'Admin', admin_path %>
        &gt;
        About the Development Team
    </div>
    <div class="col-xs-1"></div>
</div>

<div class="row"><br/></div>

<div class="row">
    <div class="col-xs-1"></div>
    <div class="col-xs-10">
        <small>
            <p>The PAX Tabletop Library "mk" system was originally created by Joe Greathead [Mojo Jojo].</p>
            <p>Our development team includes:</p>
            <ul>
                <li>Joe Greathead [Mojo Jojo]</li>
                <li>Suzi Dao [Bluebombardier]</li>
                <li>Glenn Hollingsworth [Mebibyte]</li>
            </ul>
            <p>Our team commits their free time and energy in order to make this system as effective as possible. Your feedback and suggestions are invaluable to us! Please submit any suggestions or ideas you have to improve this app by using the suggestion feature found at the bottom of every page.</p>
            <p>
                <em>Interested in joining the dev team? Speak to your Deputy or department Manager!</em>
            </p>
        </small>
    </div>
    <div class="col-xs-1"></div>
</div>

app/views/admin/backup.html.erb
<% content_for :title, 'Cloud Backup' %>

<div class="row">
    <div class="col-xs-8">
        <%= link_to 'Admin', admin_path %>
        &gt;
        Backup to Cloud
    </div>
</div>

<div class="row">
    <div class="col-xs-2"></div>
    <div class="col-xs-8" style="text-align: center;">
        <p>
            Please do not use this feature unless you're a manager.
        </p>
        <input type="button" class="btn btn-primary" id="backup-btn" value="Sync Database to Dropbox" <%= ((Event.is_live && !Event.current.is_last_day?) || !DropboxUtil.configured?) ? 'disabled' : nil %> />
        <br/>
        <% if !DropboxUtil.configured? %>
            <p>
                <small class="alert alert-text-box alert-warning"><%= DropboxUtil::MSG_NO_CONFIG %></small>
            </p>
        <% elsif Event.is_live && !Event.current.is_last_day? %>
            <p>
                <small class="alert alert-text-box alert-warning">This action is disabled during a live event.</small>
            </p>
        <% end %>
        <p>
            <small class="alert alert-text-box alert-warning">
                This action requires internet connection and will block all other transactions!!!
            </small>
        </p>
        <p>
            Syncing the database to Dropbox can take a few minutes.
            <br/>
            Please do not reload or navigate to another page until complete.
        </p>
        <p id="backup-result" class="alert alert-info" style="display: none;"></p>
    </div>
</div>

<div class="row">
    <div class="col-xs-1"></div>
    <div class="col-xs-10" style="text-align: center;">
        <div class="loading-animation" style="opacity: 0;">
            <svg width="124px" height="124px" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 100 100" preserveAspectRatio="xMidYMid" class="uil-gears">
                <rect x="0" y="0" width="100" height="100" fill="none" class="bk"></rect>
                <g transform="translate(-20,-20)">
                    <path data-event="<%= Event.current.short_name %>" d="M79.9,52.6C80,51.8,80,50.9,80,50s0-1.8-0.1-2.6l-5.1-0.4c-0.3-2.4-0.9-4.6-1.8-6.7l4.2-2.9c-0.7-1.6-1.6-3.1-2.6-4.5 L70,35c-1.4-1.9-3.1-3.5-4.9-4.9l2.2-4.6c-1.4-1-2.9-1.9-4.5-2.6L59.8,27c-2.1-0.9-4.4-1.5-6.7-1.8l-0.4-5.1C51.8,20,50.9,20,50,20 s-1.8,0-2.6,0.1l-0.4,5.1c-2.4,0.3-4.6,0.9-6.7,1.8l-2.9-4.1c-1.6,0.7-3.1,1.6-4.5,2.6l2.1,4.6c-1.9,1.4-3.5,3.1-5,4.9l-4.5-2.1 c-1,1.4-1.9,2.9-2.6,4.5l4.1,2.9c-0.9,2.1-1.5,4.4-1.8,6.8l-5,0.4C20,48.2,20,49.1,20,50s0,1.8,0.1,2.6l5,0.4 c0.3,2.4,0.9,4.7,1.8,6.8l-4.1,2.9c0.7,1.6,1.6,3.1,2.6,4.5l4.5-2.1c1.4,1.9,3.1,3.5,5,4.9l-2.1,4.6c1.4,1,2.9,1.9,4.5,2.6l2.9-4.1 c2.1,0.9,4.4,1.5,6.7,1.8l0.4,5.1C48.2,80,49.1,80,50,80s1.8,0,2.6-0.1l0.4-5.1c2.3-0.3,4.6-0.9,6.7-1.8l2.9,4.2 c1.6-0.7,3.1-1.6,4.5-2.6L65,69.9c1.9-1.4,3.5-3,4.9-4.9l4.6,2.2c1-1.4,1.9-2.9,2.6-4.5L73,59.8c0.9-2.1,1.5-4.4,1.8-6.7L79.9,52.6 z M50,65c-8.3,0-15-6.7-15-15c0-8.3,6.7-15,15-15s15,6.7,15,15C65,58.3,58.3,65,50,65z" fill="#009ddc">
                        <animateTransform attributeName="transform" type="rotate" from="90 50 50" to="0 50 50" dur="1s" repeatCount="indefinite"></animateTransform>
                    </path>
                </g>
                <g transform="translate(20,20) rotate(15 50 50)">
                    <path d="M79.9,52.6C80,51.8,80,50.9,80,50s0-1.8-0.1-2.6l-5.1-0.4c-0.3-2.4-0.9-4.6-1.8-6.7l4.2-2.9c-0.7-1.6-1.6-3.1-2.6-4.5 L70,35c-1.4-1.9-3.1-3.5-4.9-4.9l2.2-4.6c-1.4-1-2.9-1.9-4.5-2.6L59.8,27c-2.1-0.9-4.4-1.5-6.7-1.8l-0.4-5.1C51.8,20,50.9,20,50,20 s-1.8,0-2.6,0.1l-0.4,5.1c-2.4,0.3-4.6,0.9-6.7,1.8l-2.9-4.1c-1.6,0.7-3.1,1.6-4.5,2.6l2.1,4.6c-1.9,1.4-3.5,3.1-5,4.9l-4.5-2.1 c-1,1.4-1.9,2.9-2.6,4.5l4.1,2.9c-0.9,2.1-1.5,4.4-1.8,6.8l-5,0.4C20,48.2,20,49.1,20,50s0,1.8,0.1,2.6l5,0.4 c0.3,2.4,0.9,4.7,1.8,6.8l-4.1,2.9c0.7,1.6,1.6,3.1,2.6,4.5l4.5-2.1c1.4,1.9,3.1,3.5,5,4.9l-2.1,4.6c1.4,1,2.9,1.9,4.5,2.6l2.9-4.1 c2.1,0.9,4.4,1.5,6.7,1.8l0.4,5.1C48.2,80,49.1,80,50,80s1.8,0,2.6-0.1l0.4-5.1c2.3-0.3,4.6-0.9,6.7-1.8l2.9,4.2 c1.6-0.7,3.1-1.6,4.5-2.6L65,69.9c1.9-1.4,3.5-3,4.9-4.9l4.6,2.2c1-1.4,1.9-2.9,2.6-4.5L73,59.8c0.9-2.1,1.5-4.4,1.8-6.7L79.9,52.6 z M50,65c-8.3,0-15-6.7-15-15c0-8.3,6.7-15,15-15s15,6.7,15,15C65,58.3,58.3,65,50,65z" fill="#9f9fab">
                        <animateTransform attributeName="transform" type="rotate" from="0 50 50" to="90 50 50" dur="1s" repeatCount="indefinite"></animateTransform>
                    </path>
                </g>
            </svg>
        </div>
    </div>
    <div class="col-xs-1"></div>
</div>

<script>
    $(document).ready(function(){
        $('#backup-btn').click(function(){
            // show animation
            var _me = $(this);
            _me.attr('disabled', true);

            $('#backup-result').text('').hide();

            $('.loading-animation').animate({ opacity: 1.0 }, 250);
            // post to backup endpoint
            $.ajax({
                url: '/backup',
                method: 'post',
                dataType: 'json',
                success: function(){

                },
                complete: function(data){
                    $('.loading-animation').animate({ opacity: 0.0 }, 250);
                    _me.removeAttr('disabled');
                    $('#backup-result').text(data.responseJSON.message).show();
                }
            });
            // hide animation on success or error
        });
    });
</script>

app/views/admin/cull.html.erb
<% content_for :title, 'Cull Game' %>

<div class="row">
    <div class="col-xs-8">
        <%= link_to 'Admin', admin_path %>
        &gt;
        Cull Game
    </div>
    <div class="col-xs-2"></div>
</div>

<div class="row">
    <div class="col-xs-12" style="text-align: center;">
        <h3>
            Cull Game
        </h3>
        <p>This will remove a game copy from the system.</p>
    </div>
</div>

<div class="row">
    <div class="col-xs-1"></div>
    <div class="col-xs-10 input-icons" style="text-align:center;">
        <input type="text" id="cull-barcode" class="form-control" name="barcode" placeholder="Scan GAME's barcode here." autofocus />
        <i class="bi bi-dice-3-fill"></i>
    </div>
    <div class="col-xs-1"></div>
</div>

<div id="game-display"></div>

<script>
    $(document).ready(function(){
        $('#cull-barcode').change(function(){
            $.get('/admin/cull', {"barcode": $(this).val()}, null, 'script');
        });
    });

    function cull_valuable(barcode) {
        $.get('/admin/cull', {"barcode": barcode, approve: true}, null, 'script');
    }
</script>

app/views/admin/cull.js.erb
$('#game-display').html('<%= escape_javascript(render 'game') %>');
$('#cull-barcode').val('');

app/views/admin/events.html.erb
<% content_for :title, 'Events Mgmt' %>
<%= javascript_pack_tag 'my_js' %>
<div class="row">
    <div class="col-xs-6">
        <%= link_to 'Admin', admin_path %>
        &gt;
        Events
    </div>
</div>

<div class="row"><br/></div>

<div class="row">
    <div class="col-xs-2">
        <input type="button" class="btn btn-primary" id="add-event-btn" value="Add Event" />
    </div>
    <div class="col-xs-10"></div>
</div>

<div class="row"><br/></div>

<table class="table table-striped" id="events-table">
    <tr>
        <th class="col-xs-3">
            Event
        </th>
        <th class="col-xs-2">
            Location
        </th>
        <th class="col-xs-2">
            Start Date
        </th>
        <th class="col-xs-2">
            End Date
        </th>
        <th class="col-xs-1" style="text-align: center;">
            UTC Offset
        </th>
        <th class="col-xs-2"></th>
    </tr>
    <% @events.each do |event| %>
        <%= render partial: 'events/event', locals: { event: event } %>
    <% end %>
</table>

<script>

    $(document).ready(function(){
        $('#add-event-btn').click(function(){
            if($('#events-table').find('tr[data-event-id=""]').length <= 0){
                $.get('/admin/events/edit', null, null, 'script');
            }
        });

        $('#events-table').delegate('.edit-event-btn', 'click', function(){
            $.get('/admin/events/edit', { id: $(this).parents('tr').data('event-id') }, null, 'script');
        }).delegate('.cancel-event-btn', 'click', function(){
            $.get('/admin/events/cancel', { id: $(this).parents('tr').data('event-id') }, null, 'script');
        }).delegate('.save-event-btn', 'click', function(){
            var row = $(this).parents('tr'),
                data = row.find('input').serializeArray();
            $.ajax({
                url: '/admin/events/' + row.data('event-id'),
                data: data,
                method: 'put',
                dataType: 'script'
            });
        }).delegate('.new-event-btn', 'click', function(){
            $.ajax({
                url: '/admin/events',
                data: $(this).parents('tr').find('input').serializeArray(),
                method: 'post',
                dataType: 'script'
            });
        });
    });
</script>

app/views/admin/index.html.erb
<% content_for :title, 'Admin' %>

<div class="row text-center">
    <div class="col-xs-1"></div>
    <div class="col-xs-10">
        <div class="col-xs-12">
            <h4>
                Game Inventory Management
            </h4>
        </div>

        <div class="col-xs-12 btn-admin-container">
            <%= render 'link', path: setup_path, text: 'Setup Scanning', type: nil %>
            <%= render 'link', path: teardown_path, text: 'Teardown Scanning', type: nil %>
            <%= render 'link', path: tournament_path, text: 'Tournament Games Mgmt', type: nil %>
            <%= render 'link', path: new_game_path, text: 'Add New Game', type: nil %>
            <%= render 'link', path: cull_path, text: 'Cull Existing Game', type: nil %>
            <%= render 'link', path: storage_path, text: 'Cold Storage Mgmt', type: nil %>
        </div>

        <div class="col-xs-12">
            <h4>
                Automated Reporting
            </h4>
        </div>

        <div class="col-xs-12 btn-admin-container">
            <%= render 'link', path: purge_path, text: 'Games to Purge', type: nil %>
            <%= render 'link', path: missing_path, text: 'Missing Games', type: nil %>
        </div>

        <div class="col-xs-12">
            <h4>
                Management Features
            </h4>
        </div>

        <div class="col-xs-12 btn-admin-container">
            <p class="alert alert-warning">
                Please only use the below pages if you are a manager.
            </p>
            <%= render 'link', path: metrics_path(event: Event.current), text: 'Post Show Metrics', type: nil %>
            <%= render 'link', path: events_path, text: 'Events Mgmt', type: nil %>
            <%= render 'link', path: backup_path, text: 'Backup to Cloud', type: nil %>
            <%= render 'link', path: titles_path, text: 'Edit Titles', type: nil %>
            <%= render 'link', path: publishers_path, text: 'Edit Publishers', type: nil %>
            <%= render 'link', path: reports_path, text: 'Download Raw Reports', type: nil %>
        </div>

        <div class="col-xs-12 btn-admin-container">
            <%= render 'link', path: about_path, text: 'About the Dev Team', type: nil %>
        </div>

    </div>
</div>

app/views/admin/missing.html.erb
<% content_for :title, 'Missing Games' %>

<div class="row">
    <div class="col-xs-6">
        <%= link_to 'Admin', admin_path %>
        &gt;
        Missing Games
    </div>
</div>

<div class="row"><br /></div>

<% if Event.two_events_ago %>
    <div class="row">
        <div class="col-md-2"></div>
        <div class="col-md-8">
            <p>Titles listed here were created before <%= Event.two_events_ago.formatted_name %>, have not been through setup and teardown for this show, and have been missed during setup or teardown during at least one other show since <%= Event.two_events_ago.formatted_name %>.</p>
        </div>
        <div class="col-md-2"></div>
    </div>

    <% if Setup.where(event: Event.current).size == 0 && Teardown.where(event: Event.current).size == 0 %>
        <div class="row">
            <div class="col-md-2"></div>
            <div class="col-md-8" style="text-align: center;">
                <p>
                    <span class="glyphicon glyphicon-alert" style="color: #777;"></span>
                    Please process <%= link_to 'Setup', setup_path %> or <%= link_to 'Teardown', teardown_path %> for this show first before checking this list.
                    <span class="glyphicon glyphicon-alert" style="color: #777;"></span>
                </p>
            </div>
            <div class="col-md-2"></div>
        </div>
    <% else %>
        <div class="row">
            <table class="table table-striped">
                <tr>
                    <th class="col-xs-1">
                        Barcode
                    </th>
                    <th class="col-xs-3">
                        Title
                    </th>
                    <th class="col-xs-2">
                        Added
                    </th>
                    <th class="col-xs-2">
                        <%= Event.two_events_ago.formatted_name %>
                    </th>
                    <th class="col-xs-2">
                        <%= Event.one_event_ago.formatted_name %>
                    </th>
                    <th class="col-xs-2">
                        <%= Event.current.formatted_name %>
                    </th>
                </tr>
                <% Game.missing_games.each do |g_row| %>
                    <tr>
                        <td class="col-xs-1">
                            <%= g_row['barcode'] %>
                        </td>
                        <td class="col-xs-3">
                            <%= g_row['title'] %>
                        </td>
                        <td class="col-xs-2">
                            <%= g_row['created_at'] %>
                        </td>
                        <td class="col-xs-2">
                            <div class="alert alert-<%= g_row['three_show_setup'].nil? ? 'danger' : 'success' %>" style="margin-bottom: 0; padding: 4px; width: 45%; display: inline-block; text-align: center;">
                                S
                            </div>
                            <div class="alert alert-<%= g_row['three_show_teardown'].nil? ? 'danger' : 'success' %>" style="margin-bottom: 0; padding: 4px; width: 45%; display: inline-block; text-align: center;">
                                T
                            </div>
                        </td>
                        <td class="col-xs-2">
                            <div class="alert alert-<%= g_row['two_show_setup'].nil? ? 'danger' : 'success' %>" style="margin-bottom: 0; padding: 4px; width: 45%; display: inline-block; text-align: center;">
                                S
                            </div>
                            <div class="alert alert-<%= g_row['two_show_teardown'].nil? ? 'danger' : 'success' %>" style="margin-bottom: 0; padding: 4px; width: 45%; display: inline-block; text-align: center;">
                                T
                            </div>
                        </td>
                        <td class="col-xs-2">
                            <div class="alert alert-<%= g_row['one_show_setup'].nil? ? 'danger' : 'success' %>" style="margin-bottom: 0; padding: 4px; width: 45%; display: inline-block; text-align: center;">
                                S
                            </div>
                            <div class="alert alert-<%= g_row['one_show_teardown'].nil? ? 'danger' : 'success' %>" style="margin-bottom: 0; padding: 4px; width: 45%; display: inline-block; text-align: center;">
                                T
                            </div>
                        </td>
                    </tr>
                <% end %>
            </table>
        </div>
    <% end %>
<% else %>
    <div class="row">
        <div class="col-md-2"></div>
        <div class="col-md-8">
            <p class="alert alert-warning" style="text-align: center;">
                Data from three events or more is required in order to track missing games.
            </p>
            <br/>
            <p class="alert alert-info" style="text-align: center;">
                Please use the <%= link_to 'Teardown', teardown_path %> process in order to track inventory at the end of an event.
            </p>
        </div>
        <div class="col-md-2"></div>
    </div>
<% end %>

app/views/admin/publishers.html.erb
<% content_for :title, 'Edit Publishers' %>

<div class="row">
    <div class="col-xs-6">
        <%= link_to 'Admin', admin_path %>
        &gt;
        Publishers
    </div>
</div>

<div class="row"><br/></div>

<div class="row">
    <div class="col-xs-12 glyphicon-custom-left">
        <input type="text" id="p-search" class="form-control" name="search" placeholder="Enter search terms here."
               value="<%= @search %>" autofocus onfocus="this.value = this.value;"/>
        <span class="glyphicon glyphicon-search form-control-feedback"></span>
    </div>
</div>

<div class="row"><br/></div>

<div id="publishers-table">
    <%= render 'publishers/table' %>
</div>

<script>
    $(document).ready(function(){
        $('#publishers-table').delegate('.edit-publisher-btn', 'click', function(){
            $.get('/admin/publishers/edit', { id: $(this).parents('tr').data('publisher-id') }, null, 'script');
        }).delegate('.cancel-publisher-btn', 'click', function(){
            $.get('/admin/publishers/cancel', { id: $(this).parents('tr').data('publisher-id') }, null, 'script');
        }).delegate('.save-publisher-btn', 'click', function(){
            var row = $(this).parents('tr'),
                    data = row.find('input,select').serializeArray();

            $.ajax({
                url: '/admin/publishers/' + row.data('publisher-id'),
                data: data,
                method: 'put',
                dataType: 'script'
            });
        });
    });
</script>

app/views/admin/reports.html.erb
<% content_for :title, 'Reports' %>

<div class="row">
    <div class="col-xs-8">
        <%= link_to 'Admin', admin_path %>
        &gt;
        Database Reports
    </div>
</div>

<div class="row"><br/></div>

<div class="row">
    <div class="col-md-2"></div>
    <div class="col-md-8">
        <p>
            The below buttons will download .csv files directly to your computer. The download should begin within a couple of seconds after clicking. All information is based on data at the time of download.
        </p>
    </div>
</div>

<div class="row"><br/></div>

<div class="row">
    <div class="col-md-2"></div>
    <div class="col-md-8">
        <p>
            This file lists individual copies of all games including their title, publisher name, barcode, and whether they are tagged as "likely" for tournaments.
        </p>
    </div>
</div>

<div class="row">
    <div class="col-xs-2"></div>
    <div class="col-xs-10 text-right">
        <input type="button" class="btn btn-primary" id="copies-btn" value="Download Library by Game Copy" />
    </div>
</div>

<div class="row"><br/></div>

<div class="row">
    <div class="col-md-2"></div>
    <div class="col-md-8">
        <p>
            This file lists the library by title. Fields included are title, publisher name, whether a title is tagged as "likely" for tournament, and the number of game copies per title. <br/><br/><em>This is the default library view posted after each show.</em>
        </p>
    </div>
</div>

<div class="row">
    <div class="col-xs-2"></div>
    <div class="col-xs-10 text-right">
        <input type="button" class="btn btn-primary" id="titles-btn" value="Download Library by Title" />
    </div>
</div>

<div class="row"><br/></div>

<div class="row">
    <div class="col-md-2"></div>
    <div class="col-md-8">
        <p>
            This file lists individual checkouts for the current show only. This includes checkout time, return time, attendee barcode, game barcode, and game title. This can be used for further non-SQL analysis of the show's data not covered by the <a href="<%= metrics_path(event: Event.current) %>">Metrics</a> page or to backup a short form version of the checkout data.
        </p>
    </div>
</div>

<div class="row">
    <div class="col-xs-2"></div>
    <div class="col-xs-10 text-right">
        <input type="button" class="btn btn-primary" id="checkouts-btn" value="Download Checkouts for <%= Event.current.formatted_name %>" />
    </div>
</div>

<div class="row"><br/></div>

<div class="row">
    <div class="col-md-2"></div>
    <div class="col-md-8">
        <p>
            This file lists games that are in Cold Storage. This includes barcode, title, and publisher.
        </p>
    </div>
</div>

<div class="row">
    <div class="col-xs-2"></div>
    <div class="col-xs-10 text-right">
        <input type="button" class="btn btn-primary" id="storage-btn" value="Download Cold Storage" />
    </div>
</div>

<script>
    $(document).ready(function(){
        $('#copies-btn').click(function(){
            getFileAt('/games/csv', 'TTLibrary_Games.csv');
        });

        $('#titles-btn').click(function(){
            getFileAt('/titles/csv', 'TTLibrary_Titles.csv');
        });

        $('#checkouts-btn').click(function(){
            getFileAt('/checkouts/csv', 'TTLibrary_Checkouts_<%= Event.current.formatted_name %>.csv');
        });

        $('#storage-btn').click(function(){
            getFileAt('/storage/csv', 'TTLibrary_Storage.csv');
        });
    });

    function getFileAt(url, fileName){
        var anchor = document.createElement('a'),
            handle;
        if(typeof anchor.download != 'string'){
            handle = window.open();
        }
        $.get(url, function(data){
            var csv = 'data:attachment/csv;base64,' + btoa(data.csv);
            if(typeof anchor.download === 'string'){
                anchor.download = fileName;
                anchor.href = csv;
                anchor.click();
            } else {
                handle.location = csv;
            }
        });
    }
</script>

app/views/admin/suggestions.html.erb
<% content_for :title, 'Suggestions' %>

<div class="row">
    <div class="col-xs-12">
        <%= link_to 'Admin', admin_path %>
        &gt;
        <%= link_to 'Events', events_path %>
        &gt;
        <%= link_to 'Metrics', metrics_path(@event) %>
        &gt;
        Suggestions for <%= @event.name %>
    </div>
</div>

<div class="row">
    <h3>
        Suggestions for <%= @event.name %>
        <span style="float: right; font-size: 16px;">
            <%= @event.start_date %> to <%= @event.end_date %>
        </span>
    </h3>
</div>

<table class="table">
    <tr>
        <th class="col-xs-1" style="text-align: center;">
            Votes
        </th>
        <th class="col-xs-12">
            Title
        </th>
    </tr>
    <% @event.suggestions.by_votes.each do |s| %>
        <tr>
            <td class="col-xs-1" style="text-align: center;">
                <%= s.votes %>
            </td>
            <td class="col-xs-12">
                <%= s.title %>
            </td>
        </tr>
    <% end %>
</table>