config/routes.rb
Rails.application.routes.draw do

  root 'checkouts#index'

  get '/games', to: 'games#index', as: :games
  get '/find', to: 'checkouts#find', as: :find
  get '/admin', to: 'admin#index', as: :admin
  get '/recent', to: 'checkouts#recent', as: :recent
  get '/longest', to: 'checkouts#longest', as: :longest
  get '/loaners', to: 'loaners#index', as: :loaners

  get '/status', to: 'application#app_status', as: :status

  get '/attendee/status', to: 'attendees#status'
  post '/attendee/new', to: 'attendees#new'
  post '/checkout/new', to: 'checkouts#new'
  post '/return', to: 'checkouts#return'

  post '/groups', to: 'loaners#create'
  get '/groups/edit', to: 'loaners#edit'
  put '/groups/:id', to: 'loaners#update'
  get '/groups/cancel', to: 'loaners#cancel'
  delete '/groups/:id', to: 'loaners#delete'

  get '/loaners/group/:id', to: 'loaners#group_index', as: :group
  post '/loan', to: 'loaners#new'

  get '/groups/deleted', to: 'loaners#groups_deleted', as: :groups_deleted
  put '/groups/restore/:id', to: 'loaners#restore'

  get '/admin/setup', to: 'admin#setup', as: :setup
  get '/admin/teardown', to: 'admin#teardown', as: :teardown
  get '/admin/events', to: 'admin#events', as: :events
  get '/admin/cull', to: 'admin#cull', as: :cull
  get '/admin/new_game', to: 'admin#new_game', as: :new_game
  get '/admin/metrics/:event', to: 'admin#metrics', as: :metrics
  get '/admin/purge', to: 'admin#purge', as: :purge
  get '/admin/missing', to: 'admin#missing', as: :missing
  get '/admin/storage', to: 'admin#storage', as: :storage
  get '/admin/added/:event', to: 'admin#added_games', as: :added
  get '/admin/culled/:event', to: 'admin#culled_games', as: :culled

  put '/setup/tag', to: 'admin#setup_tag', as: :setup_tag
  put '/setup/reset', to: 'admin#reset_setup', as: :reset_setup

  post '/admin/events', to: 'events#create'
  get '/admin/events/edit', to: 'events#edit'
  put '/admin/events/:id', to: 'events#update'
  get '/admin/events/cancel', to: 'events#cancel'

  get '/titles', to: 'admin#titles'
  get '/admin/titles/edit', to: 'titles#edit'
  put '/admin/titles/:id', to: 'titles#update'
  get '/admin/titles/cancel', to: 'titles#cancel'

  get '/publishers', to: 'admin#publishers'
  get '/admin/publishers/edit', to: 'publishers#edit'
  put '/admin/publishers/:id', to: 'publishers#update'
  get '/admin/publishers/cancel', to: 'publishers#cancel'

  get '/tournament', to: 'admin#tournament_games'
  post '/admin/tournament', to: 'tournament_games#create'
  get '/admin/tournament/edit', to: 'tournament_games#edit'
  put '/admin/tournament/:id', to: 'tournament_games#update'
  get '/admin/tournament/cancel', to: 'tournament_games#cancel'
  delete '/admin/tournament/:id', to: 'tournament_games#delete'

  get '/tournament/recently_deleted', to: 'tournament_games#recently_deleted'
  put '/admin/tournament/restore/:id', to: 'tournament_games#restore'

  get '/about', to: 'admin#about'

  get '/reports', to: 'admin#reports'
  get '/games/csv', to: 'games#csv'
  get '/titles/csv', to: 'titles#csv'
  get '/checkouts/csv', to: 'checkouts#csv'
  get '/storage/csv', to: 'admin#csv'

  get '/admin/backup', to: 'admin#backup', as: :backup
  post '/backup', to: 'backup#initiate'

  get '/game/status', to: 'games#status'
  post '/game/new', to: 'games#new'
  get '/game/display', to: 'games#display'

  get '/suggestions/:event', to: 'admin#suggestions', as: :suggestions
  post '/suggest', to: 'application#suggest_a_title'

  get '/admin/stats', to: 'admin#stats'

end

app/controllers/loaners_controller.rb
class LoanersController < ApplicationController

  def index
    @groups = Group.active.order(created_at: :desc)
  end

  def create
    @group = Group.create(params.permit(:name, :description))
  end

  def edit
    @group = Group.find(params[:id]) if params[:id]
    @group = Group.new if @group.nil?
  end

  def update
    @group = Group.find(params[:id])
    @group.update(params.permit(:name, :description))
  end

  def cancel
    if params[:id].blank?
      @group = Group.new
    else
      @group = Group.find(params[:id])
    end
  end

  def delete
    @group_id = params[:id]
    @group = Group.find(@group_id)
    @message = @group.soft_delete

    @groups = Group.active.order(created_at: :desc)
  end

  def group_index
    @group = Group.find(params[:id])
    @loans_by_title_id = @group.active_loans.joins(game: :title).select('loans.id AS id', 'loans.check_out_time AS check_out_time', 'games.barcode AS barcode', 'games.title_id AS title_id', 'titles.title AS name').group_by{ |loan| loan.title_id }

    if order = params[:order]
      order = order.split(',').map(&:to_i)
      new_keys = @loans_by_title_id.keys - order
      new_keys += order
      @loans_by_title_id = new_keys.each_with_object({}) do |key, obj|
        temp = @loans_by_title_id[key]
        if temp
          obj[key] = temp
        end
      end
    end
  end

  def new
    @group = Group.find(params[:group_id])
    result = @group.loan_or_return_game(params[:game_barcode])

    render json: {
        error: result[:error],
        message: result[:message],
        removed: result[:removed]
      }
  end

  def groups_deleted
    @groups = Group.deleted
  end

  def restore
    @group = Group.find(params[:id])
    @group.update!(deleted: false)
  end

end

app/views/loaners/_form.html.erb
<tr class="edit-group-row" data-group-id="<%= @group.id %>">
    <td class="col-xs-3">
        <input type="text" class="form-control" name="name" placeholder="Group Name" value="<%= @group.name %>" />
    </td>
    <td class="col-xs-4">
        <input type="text" class="form-control" name="description" placeholder="Description" value="<%= @group.description %>" />
    </td>
    <td class="col-xs-1"></td>
    <td class="col-xs-2">
        <% if @group.new_record? %>
            <input type="button" class="btn btn-primary new-group-btn" value="Add" />
        <% else %>
            <input type="button" class="btn btn-primary save-group-btn" value="Save" />
        <% end %>
        <input type="button" class="btn btn-outline-secondary cancel-group-btn" value="Cancel" />
    </td>
    <th class="col-xs-2"></th>
</tr>

app/views/loaners/_group.html.erb
<tr class="display-group-row" data-group-id="<%= group.id %>">
    <td class="col-3">
        <%= group.name %>
    </td>
    <td class="col-4">
        <%= group.description %>
    </td>
    <td class="col-1">
        <% if group.active_loans.size > 0 %>
            <a href="<%= games_path(group: "#{group.id}", loaned: "on") %>" class="text-decoration-none">
                <%= group.active_loans.size %>
            </a>
        <% else %>
            <%= group.active_loans.size %>
        <% end %>
    </td>
    <td class="col-2">
        <input type="button" class="btn btn-outline-secondary edit-group-btn" value="Edit" />
        <% if group.active_loans.size <= 0 %>
            <input type="button" class="btn btn-danger delete-group-btn" value="Delete" />
        <% end %>
    </td>
    <th class="col-2">
        <a href="<%= group_path(group) %>">
            <input type="button" class="btn btn-primary loan-group-btn" value="Loan/Return >" />
        </a>
    </th>
</tr>

app/views/loaners/_groups_table.html.erb
<table class="table table-striped">
    <tr>
        <th class="col-3">
            Group
        </th>
        <th class="col-5">
            Description
        </th>
        <th class="col-1">
            Games
        </th>
        <th class="col-2"></th>
        <th class="col-1"></th>
    </tr>
    <% @groups.each do |group| %>
        <%= render partial: 'loaners/group', locals: { group: group } %>
    <% end %>
</table>

app/views/loaners/cancel.js.erb
var html = '';
<% unless @group.new_record? %>
    html = '<%= escape_javascript(render partial: 'group', locals: { group: @group }) %>';
<% end %>
$('[data-group-id="<%= @group.id %>"]').replaceWith(html);

app/views/loaners/create.js.erb
$('[data-group-id=""]').replaceWith('<%= escape_javascript(render partial: 'group', locals: { group: @group }) %>');

app/views/loaners/delete.js.erb
$('[data-group-id="<%= @group_id %>"]').remove();
$('#groups-table').html('<%= escape_javascript(render 'loaners/groups_table') %>');
<% if @message %>
    $.notify('<%= @message %>', 'warning');
<% end %>

app/views/loaners/edit.js.erb
var originalRow = $('tr[data-group-id="<%= @group.id %>"]'),
    html = '<%= escape_javascript(render 'form') %>';

if(originalRow.length > 0){
    originalRow.replaceWith(html);
}else{
    $('#groups-table').find('tr').first().after(html);
}

app/views/loaners/group_index.html.erb
<% content_for :title, "Loans for #{@group.name}" %>

<div class="row">
    <div class="col-xs-12">
        <%= link_to 'Loaner Groups', loaners_path, class:"text-decoration-none" %>
        &gt;
        Loan games to group "<%= @group.name %>"
    </div>
</div>

<div class="row"><br/></div>

<div class="row" id="l-row">
    <div class="col-xs-3"></div>
    <div class="col-xs-6 input-icons">
        <input type="text" id="l-barcode" class="form-control" placeholder="Enter GAME barcode to loan or return game to <%= @group.name %>." autofocus />
        <i class="bi bi-dice-3-fill"></i>
        <div id="loans-container-container">
            <div id="loans-container" class="panel-group" style="padding: 15px 15px;" role="tablist" aria-multiselectable="true">
                <% @loans_by_title_id.each do |title_id, loans| %>
                    <div class="panel panel-default">
                        <div class="panel-heading" role="tab" id="headingOne">
                            <h4 class="panel-title">
                                <a role="button" data-toggle="collapse" href="#<%= title_id %>" aria-expanded="true" aria-controls="collapseOne">
                                    <%= "#{loans.first.name} (#{pluralize(loans.length, 'copy')})" %>
                                </a>
                            </h4>
                        </div>
                        <div id="<%= title_id %>" class="panel-collapse collapse <%= loans.length > 1 ? '' : 'in' %>" role="tabpanel" aria-labelledby="headingOne">
                            <div class="list-group">
                                <% loans.each do |loan| %>
                                    <div class="list-group-item">
                                        <div class="row" style="padding-left: 15px; padding-right: 15px;">
                                            <p class="col-xs-8">
                                                <%= "#{loan.barcode} @ #{ct(loan.check_out_time).strftime('%m/%d %I:%M%P')}" %>
                                            </p>
                                            <input type="button" data-game-barcode="<%= loan.barcode %>" class="btn btn-danger col-xs-4 return-loaner-btn" value="Return Game" />
                                        </div>
                                    </div>
                                <% end %>
                            </div>
                        </div>
                    </div>
                <% end %>
            </div>
        </div>
    </div>
    <div class="col-xs-1"></div>
    <div class="col-xs-2"></div>
</div>

<script>
    
    $(document).ready(function(){
        $('#l-barcode').change(function(){
            var gBarcode = $(this).val();
            console.log(gBarcode)
            if(!bc_regex.test(gBarcode)){
                $.notify('Invalid barcode format! Barcode should be at least 7 characters long and only contain alphanumeric characters.', 'warning', 5000);
                $(this).val('');
                return;
            }

            loanOrReturnGame(gBarcode);
        });

        $('#loans-container-container').delegate('.return-loaner-btn', 'click', function(){
            loanOrReturnGame($(this).data('game-barcode'));
        });

        function loanOrReturnGame(barcode){
            $.post('/loan', { game_barcode: barcode, group_id: '<%= @group.id %>' }).success(function(response){
                if(response.error){
                    $.notify(response.message, 'danger');
                } else {
                    if (response && response.message){
                        $.notify(response.message);
                    }

                    var reduceFunc = function(obj, element) {
                      if (element.classList.contains("in")) {
                        obj["#" + element.id] = true;
                      }
                      return obj;
                    };

                    var mapFunc = function(element) {
                        return element.id;
                    }

                    var openSelector = Object.keys($(".panel-collapse").get().reduce(reduceFunc, {})).join(",");
                    var order = "";

                    if (response.removed) {
                        order = "?order=" + $(".panel-collapse").get().map(mapFunc).join(",");
                    }
                    
                    $("#loans-container-container").load(window.location.href + order + " #loans-container", function() {
                        $(openSelector).addClass('in');
                    });
                }
            }).error(function(){
                $.notify(DEFAULT_ERROR, 'danger');
            }).complete(function(){
                $('#l-barcode').val('');
            });
        }
    });
</script>

app/views/loaners/groups_deleted.html.erb
<% content_for :title, 'Restore Loaners Group' %>

<div class="row">
    <div class="col-xs-12">
        <%= link_to 'Loaner Groups', loaners_path %>
        &gt;
        Restore a Group
    </div>
</div>

<div class="row"><br/></div>

<table class="table table-striped" id="deleted-groups-table">
    <tr>
        <th class="col-xs-3">
            Group
        </th>
        <th class="col-xs-7">
            Description
        </th>
        <th class="col-xs-2"></th>
    </tr>
    <% @groups.each do |group| %>
        <tr data-group-id="<%= group.id %>">
            <td class="col-xs-3">
                <%= group.name %>
            </td>
            <td class="col-xs-7">
                <%= group.description %>
            </td>
            <th class="col-xs-2">
                <input type="button" class="btn btn-outline-secondary restore-group-btn" value="Restore Group" />
            </th>
        </tr>
    <% end %>
</table>

<script>
    $(document).ready(function(){
        $('#deleted-groups-table').delegate('.restore-group-btn', 'click', function(){
            $.ajax({
                url: '/groups/restore/' + $(this).parents('tr').data('group-id'),
                method: 'put',
                dataType: 'script'
            });
        });
    });
</script>

app/views/loaners/index.html.erb
<% content_for :title, 'Loaners' %>

<div class="container">
    <div class="row">
        <div class="col-6">
            <input type="button" class="btn btn-primary" id="add-group-btn" value="Add Group" />
        </div>
        <div class="col-6 text-end">
            <a href="<%= groups_deleted_path %>" class="text-decoration-none">Restore a Group</a>
        </div>
    </div>
</div>

<div class="row"><br/></div>

<div id="groups-table">
    <%= render 'loaners/groups_table' %>
</div>

<script>
    $(document).ready(function(){
        $('#add-group-btn').click(function(){
            if($('#groups-table').find('tr[data-group-id=""]').length <= 0){
                $.get('/groups/edit', null, null, 'script');
            }
        });

        $('#groups-table').delegate('.edit-group-btn', 'click', function(){
            $.get('/groups/edit', { id: $(this).parents('tr').data('group-id') }, null, 'script');
        }).delegate('.cancel-group-btn', 'click', function(){
            $.get('/groups/cancel', { id: $(this).parents('tr').data('group-id') }, null, 'script');
        }).delegate('.save-group-btn', 'click', function(){
            var row = $(this).parents('tr'),
                data = row.find('input').serializeArray();
            $.ajax({
                url: '/groups/' + row.data('group-id'),
                data: data,
                method: 'put',
                dataType: 'script'
            });
        }).delegate('.new-group-btn', 'click', function(){
            $.ajax({
                url: '/groups',
                data: $(this).parents('tr').find('input').serializeArray(),
                method: 'post',
                dataType: 'script'
            });
        }).delegate('.delete-group-btn', 'click', function(){
            var row = $(this).parents('tr');
            $.ajax({
                url: '/groups/' + row.data('group-id'),
                method: 'delete',
                dataType: 'script'
            });
        });
    });
</script>

app/views/loaners/restore.js.erb
$('tr[data-group-id="<%= @group.id %>"]')
    .find('.restore-group-btn')
    .replaceWith('<span class="glyphicon glyphicon-ok glyphicon-table"></span>');

app/views/loaners/update.js.erb
$('[data-group-id="<%= @group.id %>"]').replaceWith('<%= escape_javascript(render partial: 'group', locals: { group: @group }) %>');