config/routes.rb
Rails.application.routes.draw do

  root 'checkouts#index'

  get '/games', to: 'games#index', as: :games
  get '/find', to: 'checkouts#find', as: :find
  get '/admin', to: 'admin#index', as: :admin
  get '/recent', to: 'checkouts#recent', as: :recent
  get '/longest', to: 'checkouts#longest', as: :longest
  get '/loaners', to: 'loaners#index', as: :loaners

  get '/status', to: 'application#app_status', as: :status

  get '/attendee/status', to: 'attendees#status'
  post '/attendee/new', to: 'attendees#new'
  post '/checkout/new', to: 'checkouts#new'
  post '/return', to: 'checkouts#return'

  post '/groups', to: 'loaners#create'
  get '/groups/edit', to: 'loaners#edit'
  put '/groups/:id', to: 'loaners#update'
  get '/groups/cancel', to: 'loaners#cancel'
  delete '/groups/:id', to: 'loaners#delete'

  get '/loaners/group/:id', to: 'loaners#group_index', as: :group
  post '/loan', to: 'loaners#new'

  get '/groups/deleted', to: 'loaners#groups_deleted', as: :groups_deleted
  put '/groups/restore/:id', to: 'loaners#restore'

  get '/admin/setup', to: 'admin#setup', as: :setup
  get '/admin/teardown', to: 'admin#teardown', as: :teardown
  get '/admin/events', to: 'admin#events', as: :events
  get '/admin/cull', to: 'admin#cull', as: :cull
  get '/admin/new_game', to: 'admin#new_game', as: :new_game
  get '/admin/metrics/:event', to: 'admin#metrics', as: :metrics
  get '/admin/purge', to: 'admin#purge', as: :purge
  get '/admin/missing', to: 'admin#missing', as: :missing
  get '/admin/storage', to: 'admin#storage', as: :storage
  get '/admin/added/:event', to: 'admin#added_games', as: :added
  get '/admin/culled/:event', to: 'admin#culled_games', as: :culled

  put '/setup/tag', to: 'admin#setup_tag', as: :setup_tag
  put '/setup/reset', to: 'admin#reset_setup', as: :reset_setup

  post '/admin/events', to: 'events#create'
  get '/admin/events/edit', to: 'events#edit'
  put '/admin/events/:id', to: 'events#update'
  get '/admin/events/cancel', to: 'events#cancel'

  get '/titles', to: 'admin#titles'
  get '/admin/titles/edit', to: 'titles#edit'
  put '/admin/titles/:id', to: 'titles#update'
  get '/admin/titles/cancel', to: 'titles#cancel'

  get '/publishers', to: 'admin#publishers'
  get '/admin/publishers/edit', to: 'publishers#edit'
  put '/admin/publishers/:id', to: 'publishers#update'
  get '/admin/publishers/cancel', to: 'publishers#cancel'

  get '/tournament', to: 'admin#tournament_games'
  post '/admin/tournament', to: 'tournament_games#create'
  get '/admin/tournament/edit', to: 'tournament_games#edit'
  put '/admin/tournament/:id', to: 'tournament_games#update'
  get '/admin/tournament/cancel', to: 'tournament_games#cancel'
  delete '/admin/tournament/:id', to: 'tournament_games#delete'

  get '/tournament/recently_deleted', to: 'tournament_games#recently_deleted'
  put '/admin/tournament/restore/:id', to: 'tournament_games#restore'

  get '/about', to: 'admin#about'

  get '/reports', to: 'admin#reports'
  get '/games/csv', to: 'games#csv'
  get '/titles/csv', to: 'titles#csv'
  get '/checkouts/csv', to: 'checkouts#csv'
  get '/storage/csv', to: 'admin#csv'

  get '/admin/backup', to: 'admin#backup', as: :backup
  post '/backup', to: 'backup#initiate'

  get '/game/status', to: 'games#status'
  post '/game/new', to: 'games#new'
  get '/game/display', to: 'games#display'

  get '/suggestions/:event', to: 'admin#suggestions', as: :suggestions
  post '/suggest', to: 'application#suggest_a_title'

  get '/admin/stats', to: 'admin#stats'

end

app/views/layouts/_footer.html.erb
<div class="col-xs-12" style="margin-bottom: 6em;"></div>

<div id="suggest-row">
    <input id="suggest-btn" type="button" class="btn btn-outline-secondary" value="Suggestion Box" />
    <div id="suggest-form" style="display: none;">
        <input id="suggest-title" placeholder="Suggest a game title or a library improvement idea here!" type="text" class="form-control"/>
        <input id="save-suggest" type="button" class="btn btn-primary" value=">>" />
        <input id="cancel-suggest" type="button" class="btn btn-outline-secondary" value="X" />
    </div>
    <a href="/ReadMe.html" target="_blank" class="btn btn-outline-secondary">Read the docs >></a>
</div>

<footer class="tt-footer" data-event="<%= @current_event.short_name %>">
    <div class="col-md-3">
        <a href="/longest">
            Today's longest checkout: <span id="longest-open-checkout">00:03:05</span>
        </a>
    </div>
    <div class="col-md-6" style="text-align: center;">
        Welcome to <%= @current_event.formatted_name %>!
    </div>
    <div class="col-md-3" style="text-align: right;">
        <a href="/recent">
            <span id="open-checkouts">X</span> of <span id="total-games">X</span> games checked out
        </a>
    </div>
</footer>

app/views/layouts/_header.html.erb
<header data-event="<%= @current_event.short_name %>" style="height: 90px;">
    <div class="col-xs-1"></div>
    <div class="col-xs-10">
        <% if @current_event.is_pax %>
            <div id="tabletop-tag" class="pax-tag"></div>
            <div id="logo">
                <%= @current_event.short_name.upcase %>
            </div>
        <% elsif @current_event.is_ggc %>
            <div id="tabletop-tag" style="padding: 5px 0; width: 425px; height: 55px;">
                <%= render '/layouts/ggc_logo' %>
            </div>
            <div id="logo" style="width: 425px; color: #fff; font-weight: normal; box-shadow: -3px 3px 0 #000; background-color: #2d87c1; text-align: center;">
                TABLETOP
            </div>
        <% elsif @current_event.is_eccc %>
            <div id="tabletop-tag" class="eccc-tag" style="height: 90px;"></div>
        <% elsif @current_event.is_c2e2 %>
            <div id="tabletop-tag" class="c2e2-tag" style="height: 90px;"></div>
        <% elsif @current_event.is_shux %>
            <div id="tabletop-tag" class="shux-tag" style="height: 90px;"></div>
        <% end %>
    </div>
    <div class="col-xs-1"></div>
</header>

app/views/layouts/_nav.html.erb
<% if @current_event.is_last_day? %>
    <div class="row">
        <div class="col-md-1"></div>
        <div class="col-md-10 alert alert-info" style="text-align: center; margin: 5px 0;">
            Congratulations! You've made it to the last day of the show! Thank you for your hard work!
        </div>
    </div>
<% else %>
    <div class="row"><br/></div>
<% end %>

<nav class="row">
    <ul class="nav nav-tabs tt-nav-tabs">
        <li class="nav-item"><a class="nav-link <%= 'active' if current_page?(root_path) %>" href="<%= root_path %>">Checkout & Return</a></li>
        <li class="nav-item"><a class="nav-link <%= 'active' if current_page?(find_path) %>" href="<%= find_path %>">Find a Checkout</a></li>
        <li class="nav-item"><a class="nav-link <%= 'active' if current_page?(games_path) %>" href="<%= games_path %>">Games List</a></li>
        <li class="nav-item"><a class="nav-link <%= 'active' if params[:controller] == 'loaners' %>" href="<%= loaners_path %>">Loaners</a></li>
        <li class="nav-item"><a class="nav-link <%= 'active' if params[:controller] == 'admin' %>" href="<%= admin_path %>">Admin</a></li>
    </ul>
</nav>

<div class="row"><br/></div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    # <title>LibraryMk6</title>
    <title><%= content_for(:title) ? "TTLib - #{content_for(:title)}" : "TT Library Mk5" %></title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'layouts/header' %>
    <div id="body-wrapper" class="container">
        <%= render 'layouts/nav' %>

        <%= yield %>

    </div>

    <%= render 'layouts/footer' %>
  </body>
</html>